version: '3'
services:
  core:
    image: "${DHIS2_APPHUB_IMAGE}"
    restart: unless-stopped
    ports:
      - "${DHIS2_APPHUB_PORT}:3000"
    env_file: .apphub.env
    depends_on:
      - db
    links:
      - db
  db:
    build: ./postgres-uuid
    restart: unless-stopped
    environment:
       POSTGRES_DB: app-hub
       POSTGRES_USER: app-hub
       POSTGRES_PASSWORD: app-hub

