version: '3'
services:
  core:
    image: "${DHIS2_CORE_IMAGE}"
    restart: always
    volumes:
      - ${DHIS2_CORE_CONFIG:-./config/DHIS2_home/dhis.conf}:/DHIS2_home/dhis.conf
      - ./config/server.xml:/usr/local/tomcat/conf/server.xml
      - home:/DHIS2_home
    environment:
      CATALINA_OPTS: "-Dcontext.path='${DHIS2_CORE_CONTEXT_PATH:-}'"
    depends_on:
      - "db"
  db:
    image: "mdillon/postgis:10-alpine"
    command: "postgres -c max_locks_per_transaction=100"
    restart: always
    volumes:
      - datadb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dhis2
      POSTGRES_USER: dhis
      POSTGRES_PASSWORD: dhis
  gateway:
    image: "jwilder/nginx-proxy:alpine"
    restart: always
    ports:
      - "${DHIS2_CORE_PORT}:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.apps:/data/apps:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
  public:
    image: "jwilder/nginx-proxy:alpine"
    restart: always
    ports:
      - "${DHIS2_PUBLIC_PORT}:80"
    environment:
      DHIS2_PUBLIC_USER: dhis2
      DHIS2_PUBLIC_PASSWORD: dhis
    volumes:
      - ./config/nginx-public.conf:/etc/nginx/nginx.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
volumes:
  datadb:
  home:
