version: "3.8"

services:
  web:
    image: "${DHIS2_IMAGE:-dhis2/core:2.40.1}"
    restart: unless-stopped
    volumes:
      - files:/opt/dhis2
      - ./config/dhis.conf:/opt/dhis2/dhis.conf:ro
      - ./config/log4j2.xml:/opt/dhis2/log4j2.xml:ro
      - ./config/server.xml:/usr/local/tomcat/conf/server.xml
    environment:
      JAVA_OPTS: "-Dcontext.path='${DHIS2_CORE_CONTEXT_PATH:-}' \
              -Dlog4j2.configurationFile=/opt/dhis2/log4j2.xml"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q -S -O /dev/null http://127.0.0.1:8080/dhis-web-commons/security/login.action 2>&1| grep -q 'HTTP.*200'"]
      start_period: 120s
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true

  db:
    image: postgis/postgis
    restart: unless-stopped
    volumes:
      - postgresql:/var/lib/postgresql
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis
      POSTGRES_PASSWORD: &postgres_password dhis
      PGPASSWORD: *postgres_password # needed by psql in healthcheck
    healthcheck:
      test: ["CMD-SHELL", "psql --no-password --quiet --username $$POSTGRES_USER postgres://127.0.0.1/$$POSTGRES_DB -p 5432 --command \"SELECT 'ok'\" > /dev/null"]
      start_period: 120s
      interval: 10s
      timeout: 3s
      retries: 5
    security_opt:
      - no-new-privileges:true

  gateway:
    image: nginx
    restart: always
    depends_on:
      web:
        condition: service_healthy
    ports:
      - "${DHIS2_PORT:-8080}:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    security_opt:
      - no-new-privileges:true

volumes:
  files:
    driver: local
  postgresql:
    driver: local
